"""Document-rendering tool: render_document.

1 of the 19 registered MCP tools. Produces deterministic, pre-formatted markdown
for numerical sections of client deliverables. LLM only handles narrative prose.

Spec anchors:
- phase4-final-mcp-architecture.md § 5 Tool 16
- r3-r9-spec-corrections.md § R9 (Loi 25 footer)
- r8-founder-decisions.md § D-D (100+ guided mode AVIS DE RÉVISION JURIDIQUE)
- constraints.md § Professional disclaimer (FR default, on by default)
"""
from __future__ import annotations

from typing import Any, Optional

from scripts.pay_equity.app import tool as mcp_tool
from scripts.pay_equity.errors import MissingDataError, ValidationError
from scripts.pay_equity.models import (
    AdjustmentFile,
    CompensationFile,
    Engagement,
    EvaluationFile,
    JobClassesFile,
    OperatorMode,
)
from scripts.pay_equity.models.obligations import get_obligations_matrix


PROFESSIONAL_DISCLAIMER_FR = (
    "Ce document a été produit à l'aide d'un outil automatisé. Il doit être "
    "révisé par une personne qualifiée avant utilisation aux fins de conformité "
    "à la Loi sur l'équité salariale."
)

PROFESSIONAL_DISCLAIMER_EN = (
    "This document was produced using an automated tool. It must be reviewed by "
    "a qualified person before use for compliance with the Pay Equity Act."
)

LOI_25_FOOTER_FR = (
    "## Avis de protection des renseignements personnels (Loi 25)\n\n"
    "Les renseignements personnels recueillis dans le cadre de cet exercice "
    "(composition du comité, données de rémunération par catégorie, informations "
    "de contact) sont conservés pendant au moins 6 ans, conformément à la Loi "
    "sur l'équité salariale. Pour exercer un droit d'accès, de rectification ou "
    "de suppression, communiquez avec le contact identifié au pied de cet avis."
)

LOI_25_FOOTER_EN = (
    "## Privacy notice (Quebec Law 25)\n\n"
    "Personal information collected during this exercise (committee composition, "
    "per-class compensation data, contact details) is retained for at least 6 "
    "years per the Pay Equity Act. To exercise a right of access, rectification, "
    "or deletion, contact the person identified at the foot of this notice."
)

AVIS_REVISION_JURIDIQUE_FR = (
    "**AVIS DE RÉVISION JURIDIQUE**\n\n"
    "Les documents générés par cet outil doivent être révisés par une CRHA, un "
    "avocat spécialisé en droit du travail, ou un conseiller juridique qualifié "
    "avant utilisation aux fins de conformité à la Loi sur l'équité salariale. "
    "Pour les entreprises de 100+ personnes salariées, cette révision n'est pas facultative."
)

AVIS_REVISION_JURIDIQUE_EN = (
    "**LEGAL REVIEW NOTICE**\n\n"
    "Documents generated by this tool must be reviewed by a CHRP, a labour law "
    "attorney, or a qualified legal advisor before use for compliance with the "
    "Pay Equity Act. For enterprises of 100+ employees, this review is not optional."
)

UNVERIFIED_TAG = "[UNVERIFIED]"

VALID_DOCUMENT_TYPES = (
    "evaluation_summary_table",
    "compensation_comparison_table",
    "adjustment_schedule_table",
    "retroactive_calculation_table",
    "obligations_summary",
    "job_classes_table",
    "regression_line_summary",
)


# --- Renderers -------------------------------------------------------------

def _h(text: str, level: int = 2) -> str:
    return f"{'#' * level} {text}\n\n"


def _table(header: list[str], rows: list[list[str]]) -> str:
    sep = ["---" for _ in header]
    out = "| " + " | ".join(header) + " |\n"
    out += "| " + " | ".join(sep) + " |\n"
    for r in rows:
        out += "| " + " | ".join(r) + " |\n"
    return out + "\n"


def _fmt_money(v: float) -> str:
    return f"{v:,.2f}".replace(",", " ").replace(".", ",")


def _fmt_pct(v: float) -> str:
    return f"{v:.1f}%".replace(".", ",")


# --- Assemblers ------------------------------------------------------------
# Pure helpers that build the file-shaped models the renderers expect from the
# per-entity backend dicts the orchestrator passes in (OR-8). The orchestrator
# fetches via payequity_get_*/list_* and reassembles the file shape here; no
# network/MCP call lives in this module.

def assemble_evaluation_file(evaluation: dict) -> EvaluationFile:
    """Build an EvaluationFile from the backend evaluation-grid dict.

    Accepts either the full file-shaped dict ({grid, class_scores, ...}) or the
    per-entity getters reassembled into that shape by the orchestrator.
    """
    return EvaluationFile.model_validate(evaluation)


def assemble_job_classes_file(job_classes: dict) -> JobClassesFile:
    """Build a JobClassesFile from the backend job-classes dict."""
    return JobClassesFile.model_validate(job_classes)


def assemble_compensation_file(compensation: dict) -> CompensationFile:
    """Build a CompensationFile from the backend compensation dict.

    The orchestrator reassembles comparison_results / regression / global_comparison
    (from payequity_list_comparison_results / get_regression_result / get_global_result
    / get_compensation_meta) into the file shape before passing it in (OR-5/OR-8).
    """
    return CompensationFile.model_validate(compensation)


def assemble_adjustment_file(adjustments: dict) -> AdjustmentFile:
    """Build an AdjustmentFile from the backend adjustments dict.

    The orchestrator reassembles class_adjustments / payment_schedule /
    retroactive_events (with interest_breakdown) into the file shape (OR-8).
    """
    return AdjustmentFile.model_validate(adjustments)


def _render_evaluation_summary_table(
    eval_file: EvaluationFile, jc_file: JobClassesFile, language: str
) -> str:
    title = "Sommaire d'évaluation des catégories" if language == "fr" else "Evaluation summary by class"
    cols_label = ("Catégorie", "Titre", "Prédominance", "Total", "Qualifications", "Responsabilités", "Effort", "Conditions") if language == "fr" else ("Class", "Title", "Predominance", "Total", "Qualifications", "Responsibilities", "Effort", "Conditions")

    score_lookup = {s.class_id: s for s in eval_file.class_scores}
    sf_lookup = {sf.id: sf for sf in eval_file.grid.sub_factors}

    rows: list[list[str]] = []
    payload = []
    for cls in jc_file.classes:
        s = score_lookup.get(cls.id)
        if not s:
            continue
        by_dim: dict[str, int] = {"qualifications": 0, "responsibilities": 0, "effort": 0, "conditions": 0}
        for sid, pts in s.scores.items():
            sf = sf_lookup.get(sid)
            if sf:
                by_dim[sf.dimension] = by_dim.get(sf.dimension, 0) + int(pts)
        payload.append((cls, s.total_score, by_dim))
    payload.sort(key=lambda x: x[1], reverse=True)
    for cls, total, by_dim in payload:
        rows.append([
            cls.id,
            cls.title,
            cls.predominance.value if cls.predominance else "",
            f"{total:.0f}",
            str(by_dim.get("qualifications", 0)),
            str(by_dim.get("responsibilities", 0)),
            str(by_dim.get("effort", 0)),
            str(by_dim.get("conditions", 0)),
        ])
    return _h(title) + _table(list(cols_label), rows)


def _render_compensation_comparison_table(comp: CompensationFile, language: str) -> str:
    title = "Comparaison des rémunérations" if language == "fr" else "Compensation comparison"
    cols = (
        ("Catégorie féminine", "Méthode", "Comparateur", "Rém. féminine ($)", "Rém. masculine ($)", "Écart ($)", "Écart (%)", "Ajustement requis")
        if language == "fr"
        else ("Female class", "Method", "Comparator", "Female comp ($)", "Male comp ($)", "Gap ($)", "Gap (%)", "Adj. required")
    )
    rows = []
    has_unverified = False
    for r in comp.comparison_results:
        if r.data_status == "UNVERIFIED":
            has_unverified = True
            adj_label = UNVERIFIED_TAG
        else:
            adj_label = (
                ("Oui" if language == "fr" else "Yes")
                if r.requires_adjustment
                else ("Non" if language == "fr" else "No")
            )
        rows.append([
            r.female_class_id,
            r.comparison_method,
            r.male_comparator_id or "—",
            _fmt_money(r.female_compensation),
            _fmt_money(r.male_compensation),
            _fmt_money(r.gap_hourly),
            _fmt_pct(r.gap_percentage),
            adj_label,
        ])
    body = _h(title) + _table(list(cols), rows)

    # R1 H-1: surface the UNVERIFIED block when global comparison lacks a
    # supplied reference compensation. Affichage cannot claim "no gap" without
    # the prescribed-comparator tariff (RLRQ E-12.001 r.2).
    if has_unverified or (
        comp.global_comparison and comp.global_comparison.data_status == "UNVERIFIED"
    ):
        prefix = (
            f"\n{UNVERIFIED_TAG} — Comparaison globale (RLRQ E-12.001 r.2) : "
            "compensation de référence non fournie. Les écarts affichés ne peuvent "
            "pas être considérés conformes tant que le tarif prescrit n'a pas été "
            "obtenu et appliqué.\n"
            if language == "fr"
            else
            f"\n{UNVERIFIED_TAG} — Global comparison (RLRQ E-12.001 r.2): "
            "reference compensation not supplied. The gaps shown cannot be claimed "
            "compliant until the prescribed tariff is obtained and applied.\n"
        )
        body = prefix + body
    return body


def _render_adjustment_schedule_table(adj: AdjustmentFile, language: str) -> str:
    title_class = "Ajustements par catégorie" if language == "fr" else "Per-class adjustments"
    cols_class = (
        ("Catégorie", "Titre", "Écart hor. ($)", "Écart ann. ($)", "Effectifs", "Coût classe ($)")
        if language == "fr"
        else ("Class", "Title", "Gap/h ($)", "Annual gap ($)", "Incumbents", "Class cost ($)")
    )
    rows_class = []
    for a in adj.class_adjustments:
        rows_class.append([
            a.class_id,
            a.title,
            _fmt_money(a.gap_hourly),
            _fmt_money(a.gap_annual),
            str(a.incumbents),
            _fmt_money(a.total_class_cost),
        ])

    title_sched = "Échéancier de versement" if language == "fr" else "Payment schedule"
    cols_sched = (
        ("Année", "Date", "%", "% cumulatif", "Montant / personne ($)")
        if language == "fr"
        else ("Year", "Date", "%", "Cumulative %", "Per-employee amount ($)")
    )
    rows_sched = []
    for s in adj.payment_schedule:
        rows_sched.append([
            str(s.year),
            s.date.isoformat(),
            _fmt_pct(s.percentage),
            _fmt_pct(s.cumulative_percentage),
            _fmt_money(s.amount_per_employee),
        ])
    return (
        _h(title_class)
        + _table(list(cols_class), rows_class)
        + _h(title_sched)
        + _table(list(cols_sched), rows_sched)
    )


def _render_retroactive_calculation_table(adj: AdjustmentFile, language: str) -> str:
    title = "Calcul rétroactif (intérêts par période de paie)" if language == "fr" else "Retroactive calculation (per-pay-period interest)"
    note = (
        f"\n*{UNVERIFIED_TAG} : valeurs fondées sur la méthode CNESST par période de paie. "
        f"Marquage levé une fois la feuille Excel CNESST appariée.*\n\n"
        if language == "fr"
        else f"\n*{UNVERIFIED_TAG}: values use the CNESST per-pay-period method. "
        f"Tag is removed once matched against the firewalled CNESST Excel.*\n\n"
    )

    cols = (
        ("Événement", "Date", "Catégorie(s)", "Écart/h ($)", "Principal ($)", "Intérêt ($)", "Total ($)")
        if language == "fr"
        else ("Event", "Date", "Class(es)", "Gap/h ($)", "Principal ($)", "Interest ($)", "Total ($)")
    )
    rows = []
    for ev in adj.retroactive_events:
        principal = sum(b.principal_period for b in ev.interest_breakdown)
        rows.append([
            ev.event_type,
            ev.event_date.isoformat(),
            ", ".join(ev.affected_class_ids),
            _fmt_money(ev.gap_hourly_at_event),
            _fmt_money(principal),
            _fmt_money(ev.interest_accrued),
            _fmt_money(ev.total_retroactive_amount),
        ])
    out = _h(title) + note + _table(list(cols), rows)

    if adj.retroactive_events:
        sub_title = "Ventilation par période de paie" if language == "fr" else "Per-pay-period breakdown"
        sub_cols = (
            ("Événement", "Période début", "Période fin", "Heures", "Principal ($)", "Jours", "Intérêt ($)")
            if language == "fr"
            else ("Event", "Period start", "Period end", "Hours", "Principal ($)", "Days", "Interest ($)")
        )
        sub_rows = []
        for ev in adj.retroactive_events:
            for b in ev.interest_breakdown:
                sub_rows.append([
                    ev.event_type,
                    b.period_start.isoformat(),
                    b.period_end.isoformat(),
                    f"{b.hours_worked:g}",
                    _fmt_money(b.principal_period),
                    str(b.days_elapsed),
                    _fmt_money(b.interest_period),
                ])
        out += _h(sub_title) + _table(list(sub_cols), sub_rows)

    return out


def _render_obligations_summary(eng: Engagement, language: str) -> str:
    matrix = get_obligations_matrix(eng.size_tier, eng.exercise_type)
    title = "Résumé des obligations" if language == "fr" else "Obligations summary"
    out = _h(title)
    yes = "Oui" if language == "fr" else "Yes"
    no = "Non" if language == "fr" else "No"
    rows = [
        ["Tranche / Tier" if language == "fr" else "Size tier", eng.size_tier.value],
        ["Exercice / Exercise" if language == "fr" else "Exercise type", eng.exercise_type.value],
        ["Comité / Committee" if language == "fr" else "Committee required", yes if matrix["committee_required"] else no],
        ["Comité de maintien (Bill 10)" if language == "fr" else "Maintenance committee (Bill 10)", yes if matrix["maintenance_committee_required"] else no],
        ["Affichage intermédiaire" if language == "fr" else "Interim posting", yes if matrix["interim_posting_required"] else no],
        ["Période de consultation (jours)" if language == "fr" else "Consultation period (days)", str(matrix["consultation_period_days"])],
    ]
    out += _table(["Élément" if language == "fr" else "Item", "Valeur" if language == "fr" else "Value"], rows)

    out += _h("Articles applicables" if language == "fr" else "Applicable articles", level=3)
    out += "- " + "\n- ".join(matrix["article_refs"]) + "\n\n"

    out += _h("Contenu d'affichage requis" if language == "fr" else "Required posting content", level=3)
    out += "- " + "\n- ".join(matrix["posting_content_requirements"]) + "\n\n"

    out += _h("Livrables" if language == "fr" else "Deliverables", level=3)
    out += "- " + "\n- ".join(matrix["deliverables_required"]) + "\n\n"
    return out


def _render_job_classes_table(jc: JobClassesFile, language: str) -> str:
    title = "Inventaire des catégories d'emploi" if language == "fr" else "Job classes inventory"
    cols = (
        ("Catégorie", "Titre", "Effectifs", "% femmes", "Prédominance", "Méthode")
        if language == "fr"
        else ("Class", "Title", "Incumbents", "% female", "Predominance", "Method")
    )
    rows = []
    for c in jc.classes:
        rows.append([
            c.id,
            c.title,
            str(c.total_incumbents),
            _fmt_pct(c.female_percentage),
            c.predominance.value if c.predominance else "—",
            c.predominance_method.value if c.predominance_method else "—",
        ])
    return _h(title) + _table(list(cols), rows)


def _render_regression_line_summary(comp: CompensationFile, language: str) -> str:
    if not comp.regression:
        raise MissingDataError("regression not run — compare_compensation in hybrid mode required.")
    r = comp.regression

    title = "Droite de régression masculine" if language == "fr" else "Male wage line regression"
    out = _h(title)
    rows = [
        ["Ordonnée à l'origine / Intercept" if language == "fr" else "Intercept", _fmt_money(r.intercept)],
        ["Pente / Slope" if language == "fr" else "Slope", f"{r.slope:.4f}"],
        ["R²", f"{r.r_squared:.3f}"],
        ["Points de données / Data points" if language == "fr" else "Data points", str(r.data_points)],
        ["Qualité / Quality" if language == "fr" else "Quality", r.quality_assessment],
    ]
    out += _table(["Métrique" if language == "fr" else "Metric", "Valeur" if language == "fr" else "Value"], rows)
    if r.outlier_class_ids:
        out += _h("Catégories aberrantes (résidus > 2σ)" if language == "fr" else "Outlier classes (residuals > 2σ)", level=3)
        out += "- " + "\n- ".join(r.outlier_class_ids) + "\n\n"
    if r.quality_notes:
        out += f"*{r.quality_notes}*\n\n"
    return out


_PARTICIPATION_GATED_DOCS = {
    "adjustment_schedule_table",
    "compensation_comparison_table",
    "obligations_summary",
    "retroactive_calculation_table",
}


def _render_body(
    document_type: str,
    engagement: Engagement,
    language: str,
    *,
    job_classes: Optional[dict],
    evaluation: Optional[dict],
    compensation: Optional[dict],
    adjustments: Optional[dict],
) -> str:
    """Dispatch to the matching renderer, assembling the file-shaped model it needs.

    Raises MissingDataError when the orchestrator did not supply the entity the
    requested document_type requires — the same operator-facing signal the old
    on-disk reads produced.
    """
    if document_type == "evaluation_summary_table":
        if evaluation is None or job_classes is None:
            raise MissingDataError(
                "evaluation-grid.json or job-classes.json missing — score classes first."
            )
        return _render_evaluation_summary_table(
            assemble_evaluation_file(evaluation),
            assemble_job_classes_file(job_classes),
            language,
        )
    if document_type == "compensation_comparison_table":
        if compensation is None:
            raise MissingDataError("compensation.json missing — call compare_compensation first.")
        return _render_compensation_comparison_table(
            assemble_compensation_file(compensation), language
        )
    if document_type == "adjustment_schedule_table":
        if adjustments is None:
            raise MissingDataError("adjustments.json missing — call calculate_adjustments first.")
        return _render_adjustment_schedule_table(
            assemble_adjustment_file(adjustments), language
        )
    if document_type == "retroactive_calculation_table":
        if adjustments is None:
            raise MissingDataError("adjustments.json missing — call calculate_adjustments first.")
        return _render_retroactive_calculation_table(
            assemble_adjustment_file(adjustments), language
        )
    if document_type == "obligations_summary":
        return _render_obligations_summary(engagement, language)
    if document_type == "job_classes_table":
        if job_classes is None:
            raise MissingDataError("job-classes.json missing.")
        return _render_job_classes_table(assemble_job_classes_file(job_classes), language)
    if document_type == "regression_line_summary":
        if compensation is None:
            raise MissingDataError("compensation.json missing.")
        return _render_regression_line_summary(
            assemble_compensation_file(compensation), language
        )
    raise ValidationError(
        f"document_type={document_type!r} not in {VALID_DOCUMENT_TYPES}"
    )


@mcp_tool
def render_document(
    document_type: str,
    engagement: dict,
    *,
    job_classes: Optional[dict] = None,
    evaluation: Optional[dict] = None,
    compensation: Optional[dict] = None,
    adjustments: Optional[dict] = None,
    regression: Optional[dict] = None,
    participation_gate: Optional[tuple[bool, str]] = None,
    language: str = "fr",
    include_disclaimer: bool = True,
) -> dict[str, Any]:
    """Render a deterministic markdown section for client deliverables.

    7 supported doc types: evaluation_summary_table, compensation_comparison_table,
    adjustment_schedule_table, retroactive_calculation_table, obligations_summary,
    job_classes_table, regression_line_summary. The render embeds the mandatory
    professional disclaimer (FR default) and Loi 25 footer. For 100+ engagements
    in guided mode, the AVIS DE RÉVISION JURIDIQUE block is also embedded.
    Retroactive calculations carry an [UNVERIFIED] tag until the CNESST Excel
    spreadsheet is matched.

    Pure: the orchestrator fetches each entity the document_type needs via
    payequity_get_*/list_* and passes it in. `participation_gate` is the
    precomputed (ok, reason) tuple from has_participation_gate_satisfied
    (recomputed gate from maintenance.py) — this function reads no files.
    """
    if document_type not in VALID_DOCUMENT_TYPES:
        raise ValidationError(
            f"document_type={document_type!r} not in {VALID_DOCUMENT_TYPES}"
        )
    if language not in ("fr", "en"):
        raise ValidationError(f"language={language!r} not in ('fr', 'en')")

    engagement_model = Engagement.model_validate(engagement)

    # The orchestrator may pass the regression result separately (per-entity
    # getter) rather than already folded into the compensation file shape;
    # merge it in so the assembler sees a complete CompensationFile (OR-8).
    if compensation is not None and regression is not None and not compensation.get("regression"):
        compensation = {**compensation, "regression": regression}

    # R5 REG-H1: Art. 76.2.1 hard gate — refuse to render maintien deliverables
    # when the participation gate has not been satisfied. Operators see this
    # as a MissingDataError pointing them at record_participation_session.
    # The gate is the precomputed (ok, reason) tuple the orchestrator passes in.
    if (
        engagement_model.exercise_type.value == "maintenance"
        and document_type in _PARTICIPATION_GATED_DOCS
    ):
        if participation_gate is None:
            raise MissingDataError(
                "Art. 76.2.1: participation gate not evaluated — call "
                "record_participation_session before rendering this document."
            )
        ok, reason = participation_gate
        if not ok:
            raise MissingDataError(reason)

    body = _render_body(
        document_type,
        engagement_model,
        language,
        job_classes=job_classes,
        evaluation=evaluation,
        compensation=compensation,
        adjustments=adjustments,
    )

    parts: list[str] = []
    if include_disclaimer:
        disclaimer = (
            PROFESSIONAL_DISCLAIMER_FR if language == "fr" else PROFESSIONAL_DISCLAIMER_EN
        )
        parts.append(f"> *{disclaimer}*\n\n")
    parts.append(body)
    parts.append("\n")
    parts.append(LOI_25_FOOTER_FR if language == "fr" else LOI_25_FOOTER_EN)
    parts.append("\n\n")

    avis_included = False
    if engagement_model.employee_count >= 100 and engagement_model.operator_mode == OperatorMode.GUIDED:
        parts.append(
            AVIS_REVISION_JURIDIQUE_FR if language == "fr" else AVIS_REVISION_JURIDIQUE_EN
        )
        parts.append("\n\n")
        avis_included = True

    markdown = "".join(parts)

    return {
        "document_type": document_type,
        "language": language,
        "markdown": markdown,
        "disclaimer_included": include_disclaimer,
        "loi_25_footer_included": True,
        "avis_revision_juridique_included": avis_included,
    }


__all__ = [
    "AVIS_REVISION_JURIDIQUE_EN",
    "AVIS_REVISION_JURIDIQUE_FR",
    "LOI_25_FOOTER_EN",
    "LOI_25_FOOTER_FR",
    "PROFESSIONAL_DISCLAIMER_EN",
    "PROFESSIONAL_DISCLAIMER_FR",
    "UNVERIFIED_TAG",
    "VALID_DOCUMENT_TYPES",
    "assemble_adjustment_file",
    "assemble_compensation_file",
    "assemble_evaluation_file",
    "assemble_job_classes_file",
    "render_document",
]
